name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout source
    - name: Checkout
      uses: actions/checkout@v4

    # 2. Set up JDK (use 17 if your Android Gradle Plugin requires it)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # 3. Make Gradle wrapper executable
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 4. Build project
    - name: Build with Gradle
      run: ./gradlew build --stacktrace

    # 5. Run unit tests
    - name: Run Unit Tests
      run: ./gradlew test

    # 6. Run Android Lint
    - name: Run Lint Checks
      run: ./gradlew lint

    # 7. Run Detekt (if you use Kotlin static analysis)
    - name: Run Detekt
      run: ./gradlew detekt
      continue-on-error: true # avoid failing build if detekt not configured

    # 8. Run instrumented tests on emulator
    - name: Set up Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew connectedCheck
